[WIP] extract shells
scilus/tractoflow pull request #60
Opened 2022-04-28 14:33 UTC by arnaudbore

2022-05-23 13:00 UTC, GuillaumeTh requested changes
I didn't review the processes because I guessed that they were not finished. You seems to don't use your extracted shells.

2022-05-23 13:00 UTC, GuillaumeTh commented on nextflow.config
> +        minimum_fodf_shell_value=1000
Be consistent with the doc --fodf_shells.

2022-05-23 13:00 UTC, GuillaumeTh commented on USAGE
> +--thr_wm_seg
Please add documentation

2022-06-10 16:19 UTC, arnaudbore commented
Ready for testing. Should the min or max shell value be inclusive or exclusive ? @GuillaumeTh @mdesco

2022-06-14 00:16 UTC, mdesco commented
> 

Inclusive, i.e <=

2022-06-16 14:09 UTC, grahamlittlephd commented on USAGE
> +--max_dti_shell_value                       Maximum shell threshold to be consider as a DTI shell ($max_dti_shell_value).
Maybe you should state here that max_dti_shell_value is used by default, and dti_shells will overide max_dti_shell_value.  Not necessary but the multiple options might confuse a user

2022-06-20 14:30 UTC, grahamlittlephd commented
Finished testing this on openpain and Pentera 3T data.  Behaves as expected!

Nice work! I would say it's good to go!

2022-06-28 00:37 UTC, arnaudbore commented
@GuillaumeTh do you want to give it a try before I merge ?

2022-06-28 19:40 UTC, merged