[BF] fix fs input
scilus/tractoflow pull request #71
Opened 2022-12-09 20:00 UTC by arnaudbore

2022-12-30 05:17 UTC, AlexVCaron requested changes
Tested and approved, after a few minor changes. Also, I just tested with relative paths as inputs. It works really well, though it kinda unfortunate that the bind paths need a `nextflow.config` to be passed. I just seed the idea, a `--binds` or `--bind_paths` parameter could be interesting, used in both `docker.runOptions` and `singularity.runOptions`, since we can give it by command line.

2022-12-30 05:17 UTC, AlexVCaron commented on main.nf
> +                --readout $params.readout $participants_flag $clean_flag ${!fs_folder.empty() ? "--fs $params.fs" : ""} -v
If you want to make it cleaner, you could define fs_flag (fs_flag = params.fs ? "--fs $params.fs" : "") above in a variable like in the older version and use it in the script string.

2022-12-30 05:17 UTC, AlexVCaron commented on main.nf
> +                --readout $params.readout $clean_flag ${!fs_folder.empty() ? "--fs $params.fs" : ""} ${!bidsignore.empty() ? "--bids_ignore $params.bidsignore" : ""} -v
After thoughts, for readability, either setup the `fs_folder` and `bidsignore` like the clean_flag or split the command on multiple lines with `\` like 
```
scil_validate_bids.py $bids_folder tractoflow_bids_struct.json\
    --readout $params.readout $clean_flag\
    ${!fs_folder.empty() ? "--fs $params.fs" : ""}\
    ${!bidsignore.empty() ? "--bids_ignore $params.bidsignore" : ""}\
    -v

2023-01-04 15:41 UTC, arnaudbore commented on main.nf
> +                --readout $params.readout $clean_flag ${!fs_folder.empty() ? "--fs $params.fs" : ""} ${!bidsignore.empty() ? "--bids_ignore $params.bidsignore" : ""} -v
Done :)

2023-01-05 14:36 UTC, AlexVCaron reviewed
Last modif then LGTM !

2023-01-05 14:36 UTC, AlexVCaron commented on main.nf
> +                --readout $params.readout $clean_flag\
```suggestion
                $clean_flag\
                ${params.readout ? "$params.readout" : ""}\
```

2023-01-05 14:55 UTC, merged